# ===========================
# Perfil DEV
# ===========================
spring.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/crochet_recipes}
spring.data.mongodb.auto-index-creation=true

# Swagger / OpenAPI habilitado em dev
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.api-docs.path=/api-docs

# Logs de desenvolvimento
logging.level.com.crochet.recipes=DEBUG
logging.level.org.springframework.data.mongodb=INFO
